### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by thyrlian** [thyrlian/AwesomeValidation#2]
- [ ] complex layout (horizontal orientation)
- [ ] overload addValidation to support range validation
- [ ] return ArrayList<Boolean> instead of boolean at Validator#trigger() ???
- [ ] add more regex constants to RegexTemplate

**Comment by androiddev-smartside** [comment]
Any plans for android.util.Pattern support or event custom validators such as the one linked below?

http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/EmailValidator.html

**Comment by thyrlian** [comment]
@androiddev-smartside Thanks for your valuable comments :)

`android.util.Patterns` already has `EMAIL_ADDRESS`, then I would say Apache's `EmailValidator` is covered by that.  And yes, good point, I'll try to support Android Patterns type directly as a parameter for `addValidation()` method.  Thanks for that.

Regarding password confirmation validation (check if two inputs match or not), I understand it's ugly if we do it like that way, but it seems like the only way now.  I can't modify the `addValidation()` API to make it beautiful, otherwise it may break other validation parts.  But maybe it could be a brand new method, something like below:
```java
tempValidator.addConfirmationValidation(mPassword, mPasswordConfirm, "Passwords don't match");
```

Please correct me if I'm wrong.  Thanks.

**Comment by thyrlian** [comment]
@androiddev-smartside 
Done.  I've just pushed the commit for supporting android.util.Patterns.  But I don't have time now to release it on bintray.  Maybe I'll do it tonight.

**Comment by thyrlian** [comment]
@androiddev-smartside 
Just back from vacation, and released new version 1.1 to bintray, you can try it out.  Thanks.

**Comment by androiddev-smartside** [comment]
Sounds great!

I was busy myself with another project but now I'm using this again and I will let you know how it goes.
What I can tell you so far is that because I want to make in to check in order from top to bottom and my form has numeric spinners in the middle, what I ended up doing was having 2 separate validators one for the fields that are above the spinners and another validator for the fields below. 

Example code:  http://pastebin.com/D1VvcSYh

If there's a better alternative, please let me know

Btw, I'm also facing an issue that one field is receiving keyboard focus even after a sucessful validation, but I haven't investigated it yet

**Comment by thyrlian** [comment]
@androiddev-smartside

Regarding the **focus** issue, you could take a look at here:
https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/validators/Validator.java#L79

As you can see from the code, it only set focus for you whenever valid fails, and it will set focus to first failed field.  So in theory, when the validation succeeds, it should not set any focus.

For the spinners, I'll check it later when I have time.  But can you make a screenshot, it may help me understand much better.  And another question, since the spinners already provides user a set of valid choices, do you just want to validate if the choice is being made or empty?  Or something else?  Thanks.

**Comment by androiddev-smartside** [comment]
Yeah, I haven't thought of how to integrate spinner validator, but maybe what could be useful is to have support for validation groups. 
validator.addToGroup(0, MyField, "Some error");
That would make it trivial to run the validations in multiple steps, and it also would not change anything for ppl who have no such need.
